# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation
# Switched to Travis-CI.com on 2022/10/27 -CG

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
